---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release-drafter:
    uses: timmo001/workflows/.github/workflows/release-drafter-python-monorepo.yml@master
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
